# Generated by Django 2.1.5 on 2019-01-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
